name: deploy to package host

on:
  push:
    branches: [ main ]

jobs:
  PACKAGE_HOST_CD:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2 # This is the action
        with:
            node-version: 16.x
      - run: yarn
      - run: npm run build
      - run: npm run deploy-package-hub
        env:
          MODULE_HUB_APP_SECRET: ${{ secrets.MODULE_HUB_APP_SECRET }}

